version: '2'
services:
 project1wp:
    build: .
    privileged: true
    container_name: project1wp
    hostname: project1wp
    mem_limit: "1G"
    memswap_limit: "1G"
    cpuset: "2"
    image: teravisiontech/wordpress
    ports:
      - "80"
      - "22"
    restart: always
    environment:
      TERM: xterm
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "./keys:/keys"
      - "./data:/var/www/html"
