---

# Overview: Playbook para probar el módulo de docker service
# Applies to: Development
# Description:
#    Levanta un servicio de docker-compose
- hosts: all
  become: true 
  tags: ['docker']
  tasks:
    - name: stop docker-compose service
      docker_service: project_src=./devops state=absent 

    - name: start docker-compose service
      docker_service: project_src=./devops build=yes

#    - name: copy site.yml inside the wp container
#      command: docker cp devops/site.yml teracd_wp:/tmp/site.yml
    
#    - name: copy site.yml inside the wpdb container
#      command: docker cp devops/site.yml teracd_wpdb:/tmp/site.yml
#      register: output

 #   - name: debug
 #     debug: msg=output.stdout
- hosts: all
  become: true
  tags: ['dexec']
  tasks:
    - name: ansible inside docker
      command: docker exec -it project1wp bash -c 'ansible-playbook -i "localhost," -c local /tmp/site.yml --tags "build"'
#    - name: install
#      yum: name=htop state=present
- hosts: all
  become: true
  tags: ['build']
  tasks:
#    - name: ansible inside docker
#      command: docker exec -it project1wp basg -c 'ansible-playbook -i "localhost," -c local /tmp/site.yml --tags "build"'
    - name: htop install
      yum: name=htop state=present
#- hosts: all
#  become: true
#  tags: ['deploy']
#  tasks:
#    - name: down mariadb
#      command: systemctl stop mariadb
#    - command: echo "finished" >> /tmp/test2.txt
#    - name: Configure MariaDB
#      template: src=my.cnf.j2 dest=/etc/mysql/my.cnf
