---

# Overview: Playbook para probar el módulo de docker service
# Applies to: Development
# Description:
#    Levanta un servicio de docker-compose
- hosts: all
  become: true 
  tags: ['docker']
  tasks:
    - name: stop docker-compose service
      docker_service: project_src=./devops state=absent 

    - name: start docker-compose service
      docker_service: project_src=./devops build=yes

#    - name: copy site.yml inside the wp container
#      command: docker cp devops/site.yml teracd_wp:/tmp/site.yml
    
#    - name: copy site.yml inside the wpdb container
#      command: docker cp devops/site.yml teracd_wpdb:/tmp/site.yml
#      register: output

 #   - name: debug
 #     debug: msg=output.stdout
- hosts: all
  become: true
  tags: ['build']
  tasks:
    - name: test
      shell: echo "BUILD" >> /tmp/test2.txt
    - name: install
      yum: name=htop state=present
- hosts: all
  become: true
  tags: ['deploy']
  tasks:
#    - name: down mariadb
#      command: systemctl stop mariadb
    - shell: echo "finished" >> /tmp/test2.txt
#    - name: Configure MariaDB
#      template: src=my.cnf.j2 dest=/etc/mysql/my.cnf
